#!/usr/bin/env bash
# Fetch Cloudflare's published IP ranges and write the two places that need them.
# SPEC.md §11: the firewall admits only Cloudflare, and Caddy must trust only
# Cloudflare when reading `CF-Connecting-IP`.
#
#   sudo ./cloudflare-ips.sh            # write the Caddy snippet and the ufw rules
#   sudo ./cloudflare-ips.sh --caddy    # snippet only (no firewall changes)
#
# Re-run when Cloudflare changes its ranges. They change rarely; when they do, a
# stale list means new edge addresses are untrusted and those visitors appear in
# the logs as Cloudflare rather than as themselves.
#
# The ranges are deliberately NOT committed to the repository. Getting one wrong
# in either direction is a security defect — too narrow loses visitor IPs, too
# wide lets anyone spoof `CF-Connecting-IP` — so the list is fetched from the
# source at install time rather than transcribed.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/cidaplus}"
SNIPPET_DIR="$APP_DIR/caddy"
SNIPPET="$SNIPPET_DIR/cloudflare-ips.caddy"
CADDY_ONLY="${1:-}"

v4=$(curl -fsS https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS https://www.cloudflare.com/ips-v6)

if [[ -z "$v4" || -z "$v6" ]]; then
  echo "could not fetch Cloudflare ranges — leaving the existing config alone" >&2
  exit 1
fi

mkdir -p "$SNIPPET_DIR"

{
  echo "# Generated by scripts/cloudflare-ips.sh on $(date -Is). Do not edit."
  echo "# Re-run that script to refresh."
  # `static` rather than the `cloudflare` module: that one lives in
  # caddy-dynamic-clientip, which stock caddy:2.10-alpine does not carry —
  # verified, the container refuses to start with `module not registered:
  # http.ip_sources.cloudflare`.
  printf 'trusted_proxies static'
  for range in $v4 $v6; do printf ' %s' "$range"; done
  printf '\n'
} > "$SNIPPET.partial"
mv "$SNIPPET.partial" "$SNIPPET"

echo "wrote $SNIPPET ($(echo "$v4 $v6" | wc -w) ranges)"

if [[ "$CADDY_ONLY" == "--caddy" ]]; then
  exit 0
fi

if ! command -v ufw >/dev/null 2>&1; then
  echo "ufw not installed; skipped the firewall rules"
  exit 0
fi

echo "restricting 80/443 to Cloudflare"
# Drop the world-open rules provision.sh created, then re-add per range.
ufw --force delete allow 80/tcp >/dev/null 2>&1 || true
ufw --force delete allow 443/tcp >/dev/null 2>&1 || true
for range in $v4 $v6; do
  ufw allow from "$range" to any port 80,443 proto tcp >/dev/null
done
echo "done — 'ufw status numbered' to review, and keep an emergency rule for your own IP"
